version: '3.3'

services:
  postgres-test:
    image: postgres:14-alpine
    container_name: postgres-test
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "test_db"
    ports:
      - "5555:5432"